server:
  port: 8002
spring:
  application:
    name: yigou-product-test
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/aigou_product
    username: root
    password: root
mybatis-plus:
  mapper-locations: classpath:cn/ithong/yigou/mapper/*Mapper.xml
  type-aliases-package: cn.ithong.yigou.domain,cn.ithong.yigou.query
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
  instance:
    prefer-ip-address: true